stages:
  - prepare
  - build
  - deploy
  - teardown
  - external

variables:
  GIT_DEPTH: 2

.template_base:
  image:
    name: registry.kpool.at/infrastructure-core/deploy/deploy-image:latest
    entrypoint:
      - ''
  when: manual
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: ${CI_COMMIT_TAG}
        CONFIG_SUFFIX: prod
        DOCKER_HOST: "ssh://$PRODUCTION_USER@$PRODUCTION_IP:25519"

    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        VERSION: ${CI_COMMIT_BRANCH}
        CONFIG_SUFFIX: dev
        DOCKER_HOST: "ssh://$EXTERNAL_USER@$EXTERNAL_IP:25519"
  script:
    - echo "This should be extended with a script, not used directly."

.template_trigger:
  when: manual
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: ${CI_COMMIT_TAG}
        CONFIG_SUFFIX: prod
        DOCKER_HOST: "ssh://$PRODUCTION_USER@$PRODUCTION_IP:25519"

    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      variables:
        VERSION: ${CI_COMMIT_BRANCH}
        CONFIG_SUFFIX: dev
        DOCKER_HOST: "ssh://$EXTERNAL_USER@$EXTERNAL_IP:25519"
  trigger:
    strategy: depend
    project: 'infrastructure-core/deploy'